// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKqjX_edAS0RleqmX7MbE8RV9dZDVVBjo',
    appId: '1:735550352641:android:5e6c8760cc96b79cba3f00',
    messagingSenderId: '735550352641',
    projectId: 'presence-c9559',
    storageBucket: 'presence-c9559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUuuT7XwqDqWJyf8sqv-zndzLM6GRAeJ4',
    appId: '1:735550352641:ios:dea39b3145238190ba3f00',
    messagingSenderId: '735550352641',
    projectId: 'presence-c9559',
    storageBucket: 'presence-c9559.appspot.com',
    iosClientId: '735550352641-6qga52pva3sfda4a0qhv31vag2gmvng4.apps.googleusercontent.com',
    iosBundleId: 'com.asbiqal.presence',
  );
}
